/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/YgzTkCUIfHm
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Rubik } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

rubik({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function FileUploadNew() {
  return (
    <div className="flex flex-col items-center justify-center h-screen bg-background">
      <Card className="w-full max-w-md p-6 space-y-4">
        <CardHeader>
          <CardTitle>File Search</CardTitle>
          <CardDescription>Upload a file and search for a term within it.</CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="file">Upload File</Label>
            <Input id="file" type="file" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="search">Search Term</Label>
            <Input id="search" type="text" placeholder="Enter search term" />
          </div>
          <Button className="w-full">Search</Button>
        </CardContent>
        <CardFooter className="flex justify-between items-center">
          <div className="text-muted-foreground">
            <span className="font-medium">0</span> matches found
          </div>
          <Button variant="outline">Clear</Button>
        </CardFooter>
      </Card>
    </div>
  )
}
